### ISSUE TITLE
Vulkan support via MoltenVK?

### ISSUE THREAD

**Issue by a-hurst** [Halo-Michael/ppsspp-builder#1]
As of PPSSPP v1.10, official support for Vulkan on macOS (and iOS, although it's seemingly untested) [has been added](https://github.com/hrydgard/ppsspp/pull/12583) via MoltenVK. Based on the comments in the pull request it's just loaded dynamically, so if PPSSPP can find a "libMoltenVK.dylib" it'll use it, and if not it'll just offer OpenGL and Software rendering.

I'm not an iOS developer so I don't trust myself to figure out a pull request, but given the above do you think it would be possible to add Vulkan support to your automated PPSSPP builds? You could probably just rename and use the [same MoltenVK iOS binary as DolphiniOS does](https://github.com/OatmealDome/dolphin/tree/ios-jb/Externals/MoltenVK), which would save you from needing to compile it yourself.

Also, thanks so much for creating/maintaining a proper build-bot for PPSSPP on iOS! Was tired of being stuck several versions behind.

**Comment by Halo-Michael** [comment]
https://github.com/hrydgard/ppsspp/issues/10654
